version: '3.9'

services:
  flask-app:
    image: jerrygeorge/shortcast:v1
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  celery-worker:
    image: jerrygeorge/shortcast:v1
    command: celery -A app.celery worker --loglevel=info
    depends_on:
      - redis
    networks:
      - app-network
    env_file:
      - .env

  postgres:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      timeout: 3s
      retries: 5

  flower:
    image: mher/flower
    env_file:
      - .env
    environment:
      - CELERY_BROKER=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery-worker
    command: >
      celery flower
      --port=5555
      --address=0.0.0.0

volumes:
  redis_data:
  postgres_data:

networks:
  app-network:
    driver: bridge
