services:
  flask-app:
    image: jerrygeorge/shortcast:v1
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env

  postgres:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flower:
    image: mher/flower
    env_file:
      - .env
    environment:
      - CELERY_BROKER=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery-worker
    command: >
      celery flower
      --port=5555
      --address=0.0.0.0


volumes:
  redis_data:
  postgres_data:
