"""Add transcription column to episodes

Revision ID: 1b73f32f8814
Revises: 47ec7e8928aa
Create Date: 2025-01-23 20:36:12.150734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b73f32f8814'
down_revision = '47ec7e8928aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transcription', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.drop_column('transcription')

    # ### end Alembic commands ###
