"""initial migration

Revision ID: 3aeebb366944
Revises: 
Create Date: 2025-01-01 12:24:07.128318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aeebb366944'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oauth_provider', sa.Enum('TWITCH', 'GITHUB', name='providers'), nullable=False),
    sa.Column('oauth_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('profile_image_url', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='roles'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oauth_id')
    )
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uq_playlist_title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_playlist'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uq_playlist_title')
    )
    op.create_table('podcast',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('ARTS_AND_CULTURE', 'BUSINESS', 'COMEDY', 'EDUCATION', 'FICTION', 'HEALTH_AND_FITNESS', 'KIDS_AND_FAMILY', 'LEISURE', 'NEWS_AND_POLITICS', 'RELIGION', 'SCIENCE', 'SOCIETY', 'SPORTS', 'CRIME', 'TV_AND_FILM', name='categories'), nullable=False),
    sa.Column('publisher', sa.String(), nullable=False),
    sa.Column('publish_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('uq_podcast_feed_url', sa.String(), nullable=True),
    sa.Column('uq_podcast_audio_url', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_podcast'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uq_podcast_audio_url'),
    sa.UniqueConstraint('uq_podcast_feed_url')
    )
    op.create_table('episode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('publish_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('uq_episode_audio_url', sa.String(), nullable=False),
    sa.Column('podcast_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcast.id'], name='fk_podcast_episode'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uq_episode_audio_url')
    )
    op.create_table('shared_playlist',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], name='fk_playlist_shared_playlist'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_shared_playlist'),
    sa.PrimaryKeyConstraint('user_id', 'playlist_id')
    )
    op.create_table('subscription',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('podcast_id', sa.Integer(), nullable=False),
    sa.Column('subscribed_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcast.id'], name='fk_podcast_subscription'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_subscription'),
    sa.PrimaryKeyConstraint('user_id', 'podcast_id')
    )
    op.create_table('download',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('podcast_id', sa.Integer(), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('download_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], name='fk_episode_download'),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcast.id'], name='fk_podcast_download'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_download'),
    sa.PrimaryKeyConstraint('user_id', 'podcast_id', 'episode_id')
    )
    op.create_table('favourite',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('podcast_id', sa.Integer(), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('added_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], name='fk_episode_favourite'),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcast.id'], name='fk_podcast_favourite'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_favourite'),
    sa.PrimaryKeyConstraint('user_id', 'podcast_id', 'episode_id')
    )
    op.create_table('playlistitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('podcast_id', sa.Integer(), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('added_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], name='fk_episode_playlist_item'),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcast.id'], name='fk_podcast_playlist_item'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('podcast_id', sa.Integer(), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('review_text', sa.String(), nullable=True),
    sa.Column('review_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], name='fk_episode_rating'),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcast.id'], name='fk_podcast_rating'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_rating'),
    sa.PrimaryKeyConstraint('user_id', 'podcast_id', 'episode_id')
    )
    op.create_table('playlist_playlistitem',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('playlist_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], name='fk_playlist_playlist_playlist_item'),
    sa.ForeignKeyConstraint(['playlist_item_id'], ['playlistitem.id'], name='fk_playlist_item_playlist_playlist_item'),
    sa.PrimaryKeyConstraint('playlist_id', 'playlist_item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_playlistitem')
    op.drop_table('rating')
    op.drop_table('playlistitem')
    op.drop_table('favourite')
    op.drop_table('download')
    op.drop_table('subscription')
    op.drop_table('shared_playlist')
    op.drop_table('episode')
    op.drop_table('podcast')
    op.drop_table('playlist')
    op.drop_table('user')
    # ### end Alembic commands ###
