"""added roles in shared playlist table

Revision ID: 794c5e6410e8
Revises: 3aeebb366944
Create Date: 2025-01-01 15:54:56.673419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794c5e6410e8'
down_revision = '3aeebb366944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_playlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles', sa.Enum('MODERATOR', 'CONSUMERS', name='shared'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_playlist', schema=None) as batch_op:
        batch_op.drop_column('roles')

    # ### end Alembic commands ###
